####################################################
##            Preprocess Configuration            ##
####################################################
sampling_rate: 16000     # Sampling rate.
fft_size: 1024           # FFT size.
hop_size: 160            # Hop size.
win_size: 800           # Window size.
                         # If set to null, it will be the same as fft_size.
window: "hann"           # Window function.
num_mels: 80             # Number of mel basis.
fmin: 0                  # Minimum freq in mel basis calculation.
fmax: 8000
max_abs_value: 4
min_level_db: -115
ref_level_db: 20